### PR TITLE
refactor: fixups based on experiences using the component in Enarx

### PR DESCRIPTION
**Pull request by jarkkojs**

### CODE REVIEW

**Comment by jarkkojs** [comment]
Just tuned the commit message (2nd push).

**Comment by jarkkojs** [comment]
Everybody will be better off by all practical means with zero-rooted ledger. One knob less to adjust and verify that it is correct.

It reflects how we generally seam to manage this given that:

* The current heap implementation (before ledger changes) is zero-rooted when it comes to bitmap.
* The current unit tests in this crate are based on that.

At the moment with ledger changes, heap's initializer is:

```rust
    const unsafe fn new(blk: &'a mut Block<N>) -> Self {
        let brk = None;
        Self {
            blk,
            brk,
            ledger: Ledger::new(Region::new(Address::new(0), Address::new(N * Page::SIZE))),
        }
    }
```

It would like it to be:

```rust
    const unsafe fn new(blk: &'a mut Block<N>) -> Self {
        let brk = None;
        Self {
            blk,
            brk,
            ledger: Ledger::new(Address::new(N * Page::SIZE)),
        }
    }
```

Even if some rare cases this causes inconvenience (doubt it), this has also quantitative side: it gives spare 8 bytes and ledger's global storage is a scarce resource.

**Comment by jarkkojs** [comment]
@npmccallum fixing the remaining tests. the old find was not working well in mmap so I decided to make super clean implementation and separate functions. I need this for heap/enarx (once is fixed).

**Comment by jarkkojs** [comment]
@npmccallum please pull asap, needed for https://github.com/enarx/enarx/pull/1596

All these tests did not pass with earlier find and in general two separate clean functions instead of combined multi-function is here better even if some redundancy.

**Comment by npmccallum** [comment]
I reject a zero-rooted ledger. A system may manage different sections of the address space with different ledgers. They must not overlap. That will lead to hard to debug issues.

All ledgers must define their region and reject all records that do not belong in that region.

**Comment by jarkkojs** [comment]
> I reject a zero-rooted ledger. A system may manage different sections of the address space with different ledgers. They must not overlap. That will lead to hard to debug issues.
> 
> All ledgers must define their region and reject all records that do not belong in that region.

Please show me a use case where this matters.

**Comment by jarkkojs** [comment]
> > I reject a zero-rooted ledger. A system may manage different sections of the address space with different ledgers. They must not overlap. That will lead to hard to debug issues.
> > All ledgers must define their region and reject all records that do not belong in that region.
> 
> Please show me a use case where this matters.

The base address is in all possible situations stored elsewhere than the ledger. Ledger carries relative addresses, not absolute.

**Comment by jarkkojs** [comment]
I'll drop that commit, not a high priority. Just don't see any use for it.

**Comment by jarkkojs** [comment]
@npmccallum it's now rebased.

**Comment by jarkkojs** [comment]
Squashed into single commit.

**Comment by jarkkojs** [comment]
@npmccallum I'll update shim-sgx once this has been merged.

**Comment by jarkkojs** [comment]
Actually, I can update `shim-sgx` already since `Cargo.toml` points to this branch. No need to hold on that.

**Comment by jarkkojs** [comment]
https://github.com/enarx/enarx/pull/1595 has been update accordingly.

**Review by npmccallum — APPROVED** [review]

**Pull request merged**
