### PR TITLE
test: switch to rstest-based tests

### PR DESCRIPTION
**Pull request by npmccallum**
Testing was getting overly complex. To manage this better, switch to
`rstest` for parameterized tests.

Unfortunately, this also revealed a lot of bugs. I rewrote `.add()` to
pass all tests. However, `.delete()` still fails most tests.

Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>

cc @jarkkojs

### CODE REVIEW

**Comment by npmccallum** [comment]
@jarkkojs I added lots of tests for `.delete()` but they are failing. How do you want to handle this? I propose we merge this commit with tests failing and you can follow up with a patch that fixes `.delete()`.

**Comment by jarkkojs** [comment]
> @jarkkojs I added lots of tests for `.delete()` but they are failing. How do you want to handle this? I propose we merge this commit with tests failing and you can follow up with a patch that fixes `.delete()`.

Yes, +1 for merge and I'll look into fixing it.

**Comment by jarkkojs** [comment]
> Unfortunately, this also revealed a lot of bugs. I rewrote `.add()` to pass all tests. However, `.delete()` still fails most tests.

It is **fortunately**, not unfortunately :-) Fixing, or even identifying, behind shim would be way worse.

**Review by jarkkojs — APPROVED** [review]

**Comment by jarkkojs** [comment]
We are in good state in the sense that now it is only just fixing bugs, or adding little tweaks like `is_allocated()`. Otherwise, it is already feature complete for Enarx. I.e. it cannot become at least worse (as big features increase that risk).

**Pull request merged**
